"""Denoising strategies for cubical persistence diagrams. See experiments.md,
Experiment 1 pipeline step 4, and logs/exp1_log.md, Experiment 005.

Two families are covered here:
- Image-space: Anscombe variance-stabilizing transform + Gaussian-domain denoiser +
  inverse, applied before CLAHE so the Poisson-noise assumption underlying Anscombe is
  not already broken by CLAHE's local contrast reshaping.
- Diagram-space (confidence sets / bottleneck bootstrap): a single image is not an
  i.i.d. point-cloud sample, so bootstrap replicates are generated by a spatial block
  bootstrap (resampling patches with replacement) rather than a parametric noise
  model.

CheXpert-small images are pre-processed 8-bit JPEGs, not raw detector counts -- true
Poisson statistics are already only an approximation in this dataset. The Anscombe
transform below is applied directly to the [0, 1]-normalized intensity as a heuristic
VST, not a calibrated photon-count transform, and its inverse is the algebraic
inverse (not the exact-unbiased Makitalo-Foi inverse). Both are documented
simplifications, not bugs.
"""

import numpy as np
from gtda.diagrams import PairwiseDistance
from skimage import restoration

from tda_chexpr.filtration import compute_persistence_diagram


def anscombe_transform(image: np.ndarray) -> np.ndarray:
    """Forward Anscombe variance-stabilizing transform: `2 * sqrt(image + 3/8)`."""
    return 2 * np.sqrt(image + 3 / 8)


def inverse_anscombe_transform(image: np.ndarray) -> np.ndarray:
    """Algebraic inverse of `anscombe_transform`, clipped to `[0, 1]`.

    This is the simple algebraic inverse `(image / 2) ** 2 - 3/8`, not the
    exact-unbiased Makitalo-Foi inverse -- a documented simplification.
    """
    return np.clip((image / 2) ** 2 - 3 / 8, 0.0, 1.0)


def denoise_anscombe(image: np.ndarray, method: str = "wavelet") -> np.ndarray:
    """Anscombe forward -> Gaussian-domain denoiser -> inverse.

    `method="wavelet"` uses `skimage.restoration.denoise_wavelet` (`rescale_sigma=True`),
    the classic VST+wavelet pairing for Poisson-corrupted images, backed by the `pywt`
    dependency.
    """
    transformed = anscombe_transform(image)
    if method == "wavelet":
        denoised = restoration.denoise_wavelet(transformed, rescale_sigma=True)
    else:
        raise ValueError(f"Unknown denoise method: {method!r}")
    return inverse_anscombe_transform(denoised)


def block_bootstrap_image(image: np.ndarray, block_size: int, rng: np.random.Generator) -> np.ndarray:
    """Reassemble a same-shape image by resampling non-overlapping `block_size x
    block_size` patches with replacement.

    Stands in for the i.i.d.-sample bootstrap of Fasy et al. (2014), since a single
    image is not a point-cloud sample -- this is a spatial block bootstrap instead.
    Requires `image`'s height and width to each be divisible by `block_size`.
    """
    height, width = image.shape
    if height % block_size != 0 or width % block_size != 0:
        raise ValueError(f"image shape {image.shape} not divisible by block_size {block_size}")
    n_rows, n_cols = height // block_size, width // block_size

    blocks = [
        image[r * block_size : (r + 1) * block_size, c * block_size : (c + 1) * block_size]
        for r in range(n_rows)
        for c in range(n_cols)
    ]
    n_blocks = len(blocks)
    chosen = rng.integers(0, n_blocks, size=n_blocks)

    out = np.empty_like(image)
    for idx, block_idx in enumerate(chosen):
        r, c = divmod(idx, n_cols)
        out[r * block_size : (r + 1) * block_size, c * block_size : (c + 1) * block_size] = blocks[block_idx]
    return out


def bottleneck_confidence_cutoff(
    image: np.ndarray,
    n_bootstrap: int = 20,
    block_size: int = 16,
    alpha: float = 0.05,
    rng: np.random.Generator | None = None,
) -> tuple[float, np.ndarray]:
    """Estimate a confidence-set cutoff `c_n` for `image`'s persistence diagram via a
    block-bootstrap + bottleneck-distance procedure (Fasy et al. 2014, adapted).

    Returns `(c_n, diagram)` where `diagram` is the image's own (unbootstrapped)
    sublevel persistence diagram. Per Fasy et al.'s convention, features with
    persistence <= 2 * c_n should be treated as statistically indistinguishable from
    noise.
    """
    if rng is None:
        rng = np.random.default_rng()

    diagram = compute_persistence_diagram(image)

    distance = PairwiseDistance(metric="bottleneck")
    bottleneck_distances = []
    for _ in range(n_bootstrap):
        replicate = block_bootstrap_image(image, block_size=block_size, rng=rng)
        replicate_diagram = compute_persistence_diagram(replicate)
        pair = _pad_to_common_shape(diagram, replicate_diagram)
        d = distance.fit_transform(pair)[0, 1]
        bottleneck_distances.append(d)

    c_n = float(np.quantile(bottleneck_distances, 1 - alpha))
    return c_n, diagram


def _pad_to_common_shape(diagram_a: np.ndarray, diagram_b: np.ndarray) -> np.ndarray:
    """Stack two (possibly differently-sized) diagrams into gtda's batched diagram
    format, padding the shorter one with diagonal (birth, birth, dim) points so both
    have the same per-dimension point counts, as required by `PairwiseDistance`.
    """
    dims = np.unique(np.concatenate([diagram_a[:, 2], diagram_b[:, 2]]))
    padded_a, padded_b = [], []
    for dim in dims:
        sub_a = diagram_a[diagram_a[:, 2] == dim]
        sub_b = diagram_b[diagram_b[:, 2] == dim]
        n_pad = len(sub_a) - len(sub_b)
        if n_pad > 0:
            fill = sub_b[0, 0] if len(sub_b) else 0.0
            pad = np.array([[fill, fill, dim]] * n_pad)
            sub_b = np.vstack([sub_b, pad]) if len(sub_b) else pad
        elif n_pad < 0:
            fill = sub_a[0, 0] if len(sub_a) else 0.0
            pad = np.array([[fill, fill, dim]] * (-n_pad))
            sub_a = np.vstack([sub_a, pad]) if len(sub_a) else pad
        padded_a.append(sub_a)
        padded_b.append(sub_b)
    return np.stack([np.vstack(padded_a), np.vstack(padded_b)])
